### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Xen-Corp** [Loksie/KoiVM-Virtualization#1]
You are missing a few files in your source release, but thanks for even releasing it, i know people who ask for 200$ in btc for an obfuscator

**Comment by Loksie** [comment]
The release is made to contribute, not spoon-feed those who just want to make profit out of coder's work who wanted to go beyond in the obscuring scene.
If you have troubles compiling it, you may need to make few changes in the source.. Either ways, if you ever run into troubles again, please give further information
