### ISSUE TITLE
Incomplete Solution

### ISSUE THREAD

**Issue by Xen-Corp** [Loksie/KoiVM-Virtualization#3]
Can you give us a completed SLN, that doesnt have 85 errors. Yes, i have included all assemblies in the solution, No, it did not work

**Comment by Loksie** [comment]
The project works perfectly and people is already using it without requiring any help...
Look at ben/beds obfuscator, they already ripped off the protection to add it on their obfuscators, you can also find forums where the protector is being sold at gold price.

The project may have at best 2 or 3 errors that are fixed once you read up the first lines of code, 85 errors come from wrong copy of the project, are you using desktop github?

**Comment by Xen-Corp** [comment]
No, I simply downloaded, and then tried to compile it, and bed's is fucking cancer,, it was skid central. I just want to make a custom KOI, and add a contrib to your post.

**Comment by Xen-Corp** [comment]
You might just have uploaded a broken build. The stock version is just broken upon compilation, I have found the issue, confuser2.sln itself is broken

**Comment by Xen-Corp** [comment]
f you have discord, see if you can add me, so we can properly discuss this. Xen Corp.#4484

**Comment by Loksie** [comment]
May you upload a photo? Also note that downloading the solution from github website can lead into incomplete solutions sometimes, use the github app.

**Comment by Loksie** [comment]
You did not load koi with confuserex project. if you're not sure how to do that, try using desktop application, that may fix it

**Comment by Loksie** [comment]
Just add it as a plugin in confuserex ..
