### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by DevanshT02** [Loksie/KoiVM-Virtualization#7]
I'm having errors when protecting.
[ERROR] Unknown error occurred. Exception: System.NullReferenceException: Object reference not set to an instance of an object. at KoiVM.Confuser.Internal.InitializePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in C:\Users\No\Desktop\Literally everything\KoiVM-Virtualization-master\KoiVM.Confuser\Internal\InitializePhase.cs:line 83 at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in C:\Users\No\Desktop\Literally everything\KoiVM-Virtualization-master\Confuser.Core\ProtectionPipeline.cs:line 150 at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in C:\Users\No\Desktop\Literally everything\KoiVM-Virtualization-master\Confuser.Core\ConfuserEngine.cs:line 244 at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in C:\Users\No\Desktop\Literally everything\KoiVM-Virtualization-master\Confuser.Core\ConfuserEngine.cs:line 189 Failed at 11:36 AM, 0:00 elapsed.

What exactly is going wrong? I added Koi.Confuser.exe to the confuserex using the "plugin + add"

**Comment by Loksie** [comment]
Are you using Control Flow?

**Comment by Loksie** [comment]
If you are using control flow, disable it... surely that's the cause of the error(s). You may as well want to use standard CEX, the one that I posted is a random fork that I found on google long ago.
