### ISSUE TITLE
My application wont run after obfuscation

### ISSUE THREAD

**Issue by 552bb224b12ac67f3a9f94276e491563** [Loksie/KoiVM-Virtualization#8]
As the title says I have a form application and when I pass it through koiVM it wont open
Help

**Comment by Loksie** [comment]
What features did you use besides koivm?
What .net fw version?
... need more information, it is impossible for me nor anybody to help you with that little information.

**Comment by 552bb224b12ac67f3a9f94276e491563** [comment]
I used 4.6.2 framework and I used koiVM maximum settings

**Comment by 552bb224b12ac67f3a9f94276e491563** [comment]
How can I send you file in private

**Comment by Loksie** [comment]
What do you mean koivm maximum settings? Did you use it with other CEX features?

**Comment by 552bb224b12ac67f3a9f94276e491563** [comment]
I entered confuserex app in a little Edit rule... window I set preset to maximum.
I tested a little and issue seem to be renamer and contol flow but when I remove them It straight up doesnt obfuscate

**Comment by Loksie** [comment]
That's the problem.
Please, add manually koivm in confuserEX and do not use control flow with koi as your app will break.

Also, note that there is no reason for using any protection at all besides koivm and renamer, if koivm is defeated, the attackers will laugh at the following layers.
